### ISSUE TITLE
Document the officially supported conditions in MR,XR,XRD,Provider

### ISSUE THREAD

**Issue by gberche-orange** [crossplane/docs#235]
### Expected

As a crossplane user,
in order to rely on resource conditions
I need the conditions to be documented

E.g, is it sufficient to wait for condition type=Ready on a MR to ensure its success

```
apiVersion: database.gcp.crossplane.io/v1beta1
kind: CloudSQLInstance
[...]
status:
  atProvider:
[...]
  conditions:
  - lastTransitionTime: "2022-11-24T17:20:31Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2022-12-14T19:29:37Z"
    message: 'update failed: cannot update the CloudSQL instance: googleapi: Error
      400: Invalid request: Project [...]
    reason: ReconcileError
    status: "False"
    type: Synced
```

```
apiVersion: sql.gcp.upbound.io/v1beta1
kind: DatabaseInstance
[...]
conditions:
  - lastTransitionTime: "2022-12-12T17:50:49Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2022-12-12T16:02:17Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2022-12-12T17:50:26Z"
    reason: Finished
    status: "True"
    type: AsyncOperation
  - lastTransitionTime: "2022-12-12T16:06:16Z"
    reason: Success
    status: "True"
    type: LastAsyncOperation
  - lastTransitionTime: "2022-12-14T11:10:51Z"
    reason: UpToDate
    status: "True"
    type: Test
```

### Observed

I did not find sufficient documentation so far

https://docs.crossplane.io/master/reference/troubleshoot/#resource-status-and-conditions
> Most Crossplane resources set the Ready condition. Ready represents the availability of the resource - whether it is creating, deleting, available, unavailable, binding, etc.

https://github.com/crossplane/crossplane/blob/e6b1acc6932c107c77a2ede3701eac31e017facc/design/one-pager-managed-resource-api-design.md?plain=1#L423
* Illustrates a Synced condition but does not detail it

https://github.com/upbound/upjet/blob/15411ad4889daad82962abc8063dbfbc50156d92/pkg/resource/conditions.go#L17-L64

does not provide much details over conditions
