### ISSUE TITLE
Azure getting started guide references old provider

### ISSUE THREAD

**Issue by jeanduplessis** [crossplane/docs#361]
### URL
https://docs.crossplane.io/v1.11/getting-started/provider-azure/

### What's Wrong?
The docs reference version 0.16, which was before the provider was open-sourced and asks for a license. It needs to be updated to reflect the latest version.

```yaml
cat <<EOF | kubectl apply -f -
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: upbound-provider-azure
spec:
  package: xpkg.upbound.io/upbound/provider-azure:v0.16.0
EOF
```
