### ISSUE TITLE
[Web Bug] - Composite Resources

### ISSUE THREAD

**Issue by philippart** [crossplane/docs#380]
The example [XPostgreSQLInstance ](https://docs.crossplane.io/v1.11/concepts/composition/#composite-resources-and-claims) contains the following yaml snippet which should rather belong to the Composition than the Composite Resource. The XR only contains the `environmentConfigRefs` if I understand this correctly?

In addition some example of `EnvironmentConfig` CR would be useful (like this [design doc](https://github.com/crossplane/crossplane/blob/master/design/one-pager-composition-environment.md)) with more clarity on whether the environment `xxxFieldPath` includes `data.x.y.z` or simply `x.y.z` (the examples provided: `tier.name`, `location`... seem to point to the latter).

IMHO EnvironmentConfig might deserve its own section (a shortened version of the design doc) to complement the information available in the [patch types](https://docs.crossplane.io/v1.11/concepts/composition/#patch-types) section.
```
environment:
    # EnvironmentConfigs is a list of object references that is made up of
    # name references and label selectors
    environmentConfigs:
      - type: Reference # this is the default
        ref:
          name: example-environment
      - type: Selector
        selector:
          matchLabels:
          - key: stage
            type: FromCompositeFieldPath # this is the default
            valueFromFieldPath: spec.parameters.stage
          - key: provider
            type: Value
            value: "gcp"
```
URL: /v1.11/concepts/composition/
