### ISSUE TITLE
Add info about CEL and immutable XRD fields

### ISSUE THREAD

**Issue by plumbis** [crossplane/docs#529]
### What's Missing?
https://kubernetes.io/blog/2022/09/29/enforce-immutability-using-cel/#generated-schema

We can make XRD fields immutable using the CEL stuff for CRDs.

Example in an XRD

```yaml
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                someData:
                  type: object
                  properties:
                    myField:
                      items:
                        type: string
                      type: array
                      x-kubernetes-validations:
                      - message: Value is immutable
                        rule: self == oldSelf
```

Trying to update the field will produce an error.
