### ISSUE TITLE
[Web Bug] - AWS Quickstart Part 2 - should the patches be the same?

### ISSUE THREAD

**Issue by jbw976** [crossplane/docs#550]
The example Composition manifest in https://docs.crossplane.io/v1.13/getting-started/provider-aws-part-2/#create-a-deployment-template has 2 similar patches for the bucket and the dynamodb table.  The one for the bucket uses `location` and the one for table uses `spec.location`.

I suspect though that they should actually both use `spec.location` given the XRD defined in https://docs.crossplane.io/v1.13/getting-started/provider-aws-part-2/#apply-the-api.

bucket:
```
patches:
  - type: FromCompositeFieldPath
    fromFieldPath: "location"
    toFieldPath: "spec.forProvider.region"
```

table:
```
patches:
  - type: FromCompositeFieldPath
    fromFieldPath: "spec.location"
    toFieldPath: "spec.forProvider.region"
```

URL: https://docs.crossplane.io/v1.13/getting-started/provider-aws-part-2/
