### ISSUE TITLE
Include information about Crossplane Package Dependency for configurations.

### ISSUE THREAD

**Issue by haarchri** [crossplane/docs#556]
### What's Missing?

https://docs.crossplane.io/knowledge-base/guides/troubleshoot/#handling-crossplane-package-dependency

Today, we have an example for Crossplane package dependency for providers, but there is no information indicating that this is also possible for configurations.

check: 
https://github.com/upbound/crossplane/blob/6221afd3638273aa1f66e736931619ee1153a5ac/design/one-pager-package-format-v2.md?plain=1#L197-L213

spec also not covers this information: https://github.com/crossplane/crossplane/blob/master/contributing/specifications/xpkg.md

new example could look like:

```
apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: test-configuration
  annotations:
    provider: aws
spec:
  crossplane:
    version: ">=v1.12.1-0"
  dependsOn:
    - configuration: xpkg.upbound.io/upbound/configuration-caas
      version: ">=v0.2.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-s3
      version: ">=v0.38.0"
    - provider: xpkg.upbound.io/upbound/provider-aws-kms
      version: ">=v0.38.0"
```
