### ISSUE TITLE
AWS SSO Credentials Option 2 is missing in documentation

### ISSUE THREAD

**Issue by haarchri** [crossplane/docs#559]
I made the Docs request here because the providers are transitioning to the crossplane/crossplane-contrib organization ? 

### What's Missing?
https://docs.upbound.io/providers/provider-aws/authentication/

please add in the Documentation the Option to use AWS-SSO Credentials with official provider-aws

1) Visit your AWS SSO website, locate your account, and select "Command Line" or "Programmatic Access."
![image](https://github.com/crossplane/docs/assets/21083497/be461260-44a0-456a-a533-bd6b5bff18a2)

2) Use and Copy the Credentials from Option 2 : Manually add a profile to your AWS credentials file **(Short-term credentials)** this option is helpful for PoC or Training Sessions

```
cat creds.conf
[609897127049_AdministratorAccess]
aws_access_key_id=redacted
aws_secret_access_key=redacted
aws_session_token=redacted
```

please change it to:
```
cat creds.conf
[default] # <-- requires modification.
aws_access_key_id=redacted
aws_secret_access_key=redacted
aws_session_token=redacted
```

3) Generate the Kubernetes secret using the credentials.
`kubectl -n upbound-system create secret generic aws-creds --from-file=creds=./creds.conf`

4) create providerconfig:

```
cat <<EOF | kubectl apply -f -
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: upbound-system
      name: aws-creds
      key: creds
EOF

providerconfig.aws.upbound.io/default created
```
