### ISSUE TITLE
Metadata Name Incorrectly Under Annotations

### ISSUE THREAD

**Issue by humoflife** [crossplane/docs#608]
### What's Wrong?

In crossplane documentation for importing existing resources (https://docs.crossplane.io/knowledge-base/guides/import-existing-resources/), the example says 

```

apiVersion: compute.gcp.crossplane.io/v1beta1 

kind: Network 

metadata: 

    annotations: 

        name: imported-network 

        crossplane.io/external-name: my-existing-network

```

However, `name` should be under `metadata` instead of `annotations`
