### ISSUE TITLE
ProviderConfigRef usage example seems incorrect in Managed Resources chapter

### ISSUE THREAD

**Issue by tnm-** [crossplane/docs#609]
### URL
https://docs.crossplane.io/v1.14/concepts/managed-resources/#providerconfigref
OR in source
https://github.com/crossplane/docs/blob/184fcc1435aabfb0183a9815bf52465681acf9bc/content/v1.14/concepts/managed-resources.md?plain=1#L406

### What's Wrong?

The example contains this (emphasis mine):
_For example, a managed resource references a ProviderConfig named user-keys.
This matches the name of a ProviderConfig._

```
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Instance
spec:
  forProvider:
    # Removed for brevity
  providerConfigRef: user-keys
```

Either I'm missing some magic (which I haven't found in Crossplane source or in any other example) or the above should look like:

```
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Instance
spec:
  forProvider:
    # Removed for brevity
  providerConfigRef: 
    name: user-keys
```
