### ISSUE TITLE
Proxies for Providers

### ISSUE THREAD

**Issue by haarchri** [crossplane/docs#693]
### What's Missing?

please add a documentation to use Proxies for Providers

```
error message:
Status:
  At Provider:
  Conditions:
    Last Transition Time:  2024-01-31T14:10:30Z
    Message:               connect failed: cannot initialize the no-fork async external client: cannot get terraform setup: failed to configure the no-fork Azure client: failed to configure the provider: [{0 building account: could not acquire access token to parse claims: clientCredentialsToken: cannot request token: Post "https://login.microsoftonline.com/11111111-b74d-47c9-887f-56ba76591442/oauth2/v2.0/token": POST https://login.microsoftonline.com/11111111-b74d-47c9-887f-56ba76591442/oauth2/v2.0/token giving up after 5 attempt(s): Post "https://login.microsoftonline.com/11111111-b74d-47c9-887f-56ba76591442/oauth2/v2.0/token": dial tcp: lookup [login.microsoftonline.com](http://login.microsoftonline.com/) on 10.96.0.10:53: server misbehaving  []}]
```

solution:
add Company Proxies in DeploymentRuntimeConfig:

```
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: default
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
            - name: package-runtime
              env:
                - name: HTTPS_PROXY
                  value: "http://10.99.0.0:80" #<-- example proxy1
                - name: HTTP_PROXY
                  value: "http://10.88.0.0:80" #<-- example proxy2
                - name: NO_PROXY
                  value: ""
```
