### ISSUE TITLE
Document composition function credentials

### ISSUE THREAD

**Issue by negz** [crossplane/docs#762]
https://github.com/crossplane/crossplane/pull/5543 adds the ability to pass credentials to a composition function.

```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: parent
spec:
  compositeTypeRef:
    apiVersion: nop.example.org/v1alpha1
    kind: XNopResource
  mode: Pipeline
  pipeline:
  - step: example
    functionRef:
      name: function-needs-a-secret
    credentials:
    - name: credentials-for-something
      source: Secret
      secretRef:
        namespace: crossplane-system
        name: super-secret
```
