### ISSUE TITLE
[Web Bug] - Configuring Crossplane with Argo CD

### ISSUE THREAD

**Issue by pablofilgueira91** [crossplane/docs#781]
I followed this documentation but it didn't work for me
URL: https://docs.crossplane.io/latest/guides/crossplane-with-argo-cd/

I am trying to use crossplane with argocd, but in argocd I only see the claims, I cannot get argocd to show me the XR and MR created by my claim.

for example in this application only see de claim azresourcegroup named rg-testpablo
![image](https://github.com/crossplane/docs/assets/105305544/fa0bdd45-6f73-42fd-9fbe-e5fa9c03dfdb)
this is the claim
```
apiVersion: azure.upbound.io/v1alpha1
kind: azresourcegroup
metadata:
  labels:
    argocd.argoproj.io/instance: pablo-test
  name: rg-testpablo
  namespace: homo
spec:
  compositeDeletePolicy: Background
  compositionRef:
    name: xazresourcegroups
  compositionRevisionRef:
    name: xazresourcegroups-019167e
  compositionUpdatePolicy: Automatic
  resourceRef:
    apiVersion: azure.upbound.io/v1alpha1
    kind: Xazresourcegroup
    name: rg-testpablo-bdtnn
  servicename: testpablo
```
but i don’t see de XR resource
```
apiVersion: azure.upbound.io/v1alpha1
kind: Xazresourcegroup
metadata:
  labels:
    argocd.argoproj.io/instance: pablo-test
    crossplane.io/claim-name: rg-testpablo
    crossplane.io/claim-namespace: homo
    crossplane.io/composite: rg-testpablo-bdtnn
  name: rg-testpablo-bdtnn
spec:
  claimRef:
    apiVersion: azure.upbound.io/v1alpha1
    kind: azresourcegroup
    name: rg-testpablo
    namespace: homo
  compositionRef:
    name: xazresourcegroups
  compositionRevisionRef:
    name: xazresourcegroups-019167e
  compositionUpdatePolicy: Automatic
  resourceRefs:
  - apiVersion: azure.upbound.io/v1beta1
    kind: ResourceGroup
    name: rg-labs-testpablo
  servicename: testpablo
  writeConnectionSecretToRef:
    name: b0226779-becc-41ba-904b-144e4ed3746b
    namespace: crossplane-system
```
and I don’t see the MR either
```
apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    crossplane-notification: "True"
    crossplane.io/composition-resource-name: rg
    crossplane.io/external-name: rg-labs-testpablo
  labels:
    crossplane.io/claim-name: rg-testpablo
    crossplane.io/claim-namespace: homo
    crossplane.io/composite: rg-testpablo-bdtnn
  name: rg-labs-testpablo
spec:
  deletionPolicy: Delete
  forProvider:
    location: East US 2
    tags:
      feature: testpablo
      provider: crossplane
  managementPolicies:
  - '*'
  providerConfigRef:
    name: default
```
I should see something like this in crossplane
![image](https://github.com/crossplane/docs/assets/105305544/ccdf57e0-80d9-4a58-bf4f-93d525915821)
