### ISSUE TITLE
[Web Bug] - Environment Configs

### ISSUE THREAD

**Issue by cnCloXie** [crossplane/docs#938]
Wrong apiVersion in the example code

Example code from page https://docs.crossplane.io/v2.0-preview/composition/environment-configs/#patch-an-individual-resource
```
      resources:
        - name: vpc
          base:
            apiVersion: ec2.aws.m.upbound.io/v1beta1
            kind: VPC
            spec:
```

Actually it's `ec2.aws.upbound.io/v1beta1` from document https://marketplace.upbound.io/providers/upbound/provider-aws-ec2/v1.22.0/resources/ec2.aws.upbound.io/VPC/v1beta1.

URL: https://docs.crossplane.io/v2.0-preview/composition/environment-configs/
